[build]
  publish = "build"
  command = "npm run build"

[[redirects]]
  from = "/api/*"
  to = "/.netlify/functions/:splat"
  status = 200

# Return 404 for missing files instead of redirecting to index
[build.processing]
  skip_processing = true 