[build]
  command = "npm install"
  publish = "/"
  functions = "functions"

[build.environment]
  NODE_VERSION = "18"

[[redirects]]
  from = "/*"
  to = "/.netlify/functions/server"
  status = 200

# Return 404 for missing files instead of redirecting to index
[build.processing]
  skip_processing = true 